version: '2'
services:
  service-token:
    build: .
    ports:
      - '7100:3000'
      - '7101:5858'
    tty: true
    volumes:
      - './app:/app'
    command: 'npm run nodemon-start'
    container_name: service-token
    environment:
      - EXPOSED_PORT=7100
      - PORT=3000
